import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/app/globals.css";
import { cn } from "@/lib/utils";
import ThemeProvider from "@/context/ThemeProvider";
import MobileLandingNavbar from "@/components/navbar/LandingPage/MobileLandingNavbar";
import LandingNavbar from "@/components/navbar/LandingPage/LandingNavbar";

const fontMonserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PortalLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={cn("", fontMonserrat.className, process.env.NODE_ENV == "development" && 'debug-screens')}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
